"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import i18n from "./i18n";
import { I18nextProvider } from "react-i18next";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <I18nextProvider i18n={i18n} defaultNS={"translation"}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </I18nextProvider>
  );
}
