PUT  http://127.0.0.1:3000/users/3 HTTP/1.1
content-type: application/json

{
    "name": "kerrywu3",
    "age": 33
}

# DELETE  http://127.0.0.1:3000/users/1 HTTP/1.1

# GET http://127.0.0.1:3000/users/2 HTTP/1.1

# GET http://127.0.0.1:3000/users HTTP/1.1

# POST http://127.0.0.1:3000/users HTTP/1.1
# content-type: application/json

# {
#     "id": 5,
#     "name": "kerrywu3",
#     "age": 33
# }